apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: charts/podinfo
      version: '4.0.1'
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: default
      interval: 1m
  values:
    replicaCount: 2