apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: cluster/charts
      sourceRef:
        kind: GitRepository
        name: crossplane
        namespace: default
      interval: 1m